apiVersion: apps/v1
kind: Deployment
metadata:
  name: ScreenHive-API-Backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ScreenHive-API-Backend
  template:
    metadata:
      labels:
        app: ScreenHive-API-Backend
    spec:
      containers:
      - name: ScreenHive-API-Backend
        image: stearnsbq/screenhive:api
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: ScreenHive-API-Backend
spec:
  type: NodePort
  selector:
    app: ScreenHive-API-Backend
  ports:
  - port: 80
    targetPort: 8080

