apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: stearnsbq/screenhive:room-orchestrator
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
