apiVersion: apps/v1
kind: Deployment
metadata:
  name: ScreenHive-Landing-Frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ScreenHive-Landing-Frontend
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
      - name: landing
        image: stearnsbq/screenhive:landing
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: landing
spec:
  type: LoadBalancer
  selector:
    app: landing
  ports:
  - port: 80
    targetPort: 80

